# docker-compose.yml
version: '3.8'

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres_data:
